name: t36 - Constant If Condition
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Always true"
        if: true
      - run: echo "Always false"
        if: false
